---
- name: Lab 11 Solution
  hosts: all
  tasks:
    - name: Create clean-tmp cron job
      cron:
        name: "clean-tmp"
        user: root
        job: rm -rf /tmp/*
        minute: "0"
        hour: "0"
